# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "mqtt-server" do |mqtt|
    mqtt.vm.box = "generic/ubuntu2004"
    mqtt.vm.network "forwarded_port", guest: 1883, host: 1883
    # mqtt.vm.synced_folder "../data", "/vagrant_data"
    mqtt.vm.provider "virtualbox" do |vb|
      vb.name = "mqtt-server"
      vb.gui = false
      vb.cpus = 2
      vb.memory = "2048"
    end
    mqtt.vm.provision "shell", inline: <<-SHELL
      apt update
      apt upgrade -y
      apt install -y mosquitto mosquitto-clients
    SHELL
  end
end
